// ─── FitTrackr Exercise Library ───────────────────────────────────────────────
// Master list of exercises with primary and secondary muscle group mappings.
// Secondary values are fractional set counts (1.0 = full credit, 0.5 = half, etc.)
// This file lives in the app bundle — never fetched from Firestore.
// Version increment triggers incremental backfill for existing users on next login.

export const EXERCISE_LIBRARY_VERSION = 1;

// Canonical muscle group taxonomy
export const MUSCLE_GROUPS = [
  'Abductors',
  'Adductors',
  'Back',
  'Biceps',
  'Calves',
  'Cardio',
  'Chest',
  'Core',
  'Glutes',
  'Hamstrings',
  'Other',
  'Quads',
  'Shoulders',
  'Traps',
  'Triceps',
];

// Each entry:
// { name, primaryGroup, secondaryGroups: { [muscleGroup]: fractionalValue } }
export const EXERCISE_LIBRARY = [

  // ─── CHEST ────────────────────────────────────────────────────────────────
  { name: 'Banded Bench Press (Speed)',            primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Banded Speed Bench',                    primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Bench Press (Barbell)',                 primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Bench Press (Dumbbell)',                primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Bench Press (Dumbbell Partials)',       primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Cable Crossover',                       primaryGroup: 'Chest',      secondaryGroups: { Shoulders: 0.3 } },
  { name: 'Chest Dip',                             primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Chest Dip (Assisted)',                  primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Chest Fly (Dumbbell)',                  primaryGroup: 'Chest',      secondaryGroups: { Shoulders: 0.3 } },
  { name: 'Chest Press (Machine)',                 primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Deficit Pushup',                        primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Incline Barbell Press (Narrow Grip)',   primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.5 } },
  { name: 'Incline Bench Press (Barbell)',         primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.5 } },
  { name: 'Incline Bench Press (Dumbbell)',        primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.5 } },
  { name: 'Incline Bench Press (Smith Machine)',   primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.5 } },
  { name: 'Incline Chest Fly (Dumbbell)',          primaryGroup: 'Chest',      secondaryGroups: { Shoulders: 0.3 } },
  { name: 'Pec Deck (Machine)',                    primaryGroup: 'Chest',      secondaryGroups: {} },
  { name: 'Pec Deck - Shortened Crossbody',        primaryGroup: 'Chest',      secondaryGroups: {} },
  { name: 'Pin Press Bench',                       primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Plyo Chest Falls',                      primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.3 } },
  { name: 'Plyo Clapping Pushups',                 primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.3, Shoulders: 0.3 } },
  { name: 'Plyo Push Up To Plates',                primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.3, Shoulders: 0.3 } },
  { name: 'Push Up',                               primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Ring Pushup',                           primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },
  { name: 'Speed Bench Press',                     primaryGroup: 'Chest',      secondaryGroups: { Triceps: 0.5, Shoulders: 0.3 } },

  // ─── BACK ─────────────────────────────────────────────────────────────────
  { name: 'Back Extension',                        primaryGroup: 'Back',       secondaryGroups: { Glutes: 0.3, Hamstrings: 0.3 } },
  { name: 'Bent Over One Arm Row (Dumbbell)',      primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Bent Over Row (Barbell)',               primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Bent Over Row (Dumbbell)',              primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Cobra Pulls',                           primaryGroup: 'Back',       secondaryGroups: { Shoulders: 0.3 } },
  { name: 'Dante Row',                             primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Deficit Barbell Row',                   primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Freemotion Iso Lat Pulldowns',          primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Freemotion Lat Prayers',                primaryGroup: 'Back',       secondaryGroups: {} },
  { name: 'Good morning dumbbell',                 primaryGroup: 'Back',       secondaryGroups: { Hamstrings: 0.5, Glutes: 0.3 } },
  { name: 'Hammer Strength Lat Row',               primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Incline Row (Barbell)',                 primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Incline Row (Cable Home)',              primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Incline Row (Dumbbell)',                primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Iso-Lateral Row (Machine)',             primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Lat Prayer',                            primaryGroup: 'Back',       secondaryGroups: {} },
  { name: 'Lat Pulldown (Cable)',                  primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Lat Pulldown (Single Arm)',             primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Lat Pulldown - Underhand (Cable)',      primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Lat Pulldown Neutral Grip',             primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Lat Pulldowns (Narrow Grip)',           primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Low Row Narrow Grip',                   primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Meadows Row',                           primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Pendlay Row (Barbell)',                 primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Pull Up',                               primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Pull Up (Assisted)',                    primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Pull Up (Band)',                        primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Pullover (Dumbbell)',                   primaryGroup: 'Back',       secondaryGroups: { Chest: 0.3 } },
  { name: 'Rack Pull (Barbell)',                   primaryGroup: 'Back',       secondaryGroups: { Traps: 0.5, Glutes: 0.3 } },
  { name: 'Reverse Fly (Cable)',                   primaryGroup: 'Back',       secondaryGroups: { Shoulders: 0.5 } },
  { name: 'Reverse Fly (Dumbbell)',                primaryGroup: 'Back',       secondaryGroups: { Shoulders: 0.5 } },
  { name: 'Reverse Fly (Machine)',                 primaryGroup: 'Back',       secondaryGroups: { Shoulders: 0.5 } },
  { name: 'Reverse Flye Machine Single Arm',       primaryGroup: 'Back',       secondaryGroups: { Shoulders: 0.5 } },
  { name: 'Romanian Deadlift (Barbell)',           primaryGroup: 'Back',       secondaryGroups: { Hamstrings: 0.5, Glutes: 0.5 } },
  { name: 'Romanian Deadlift (Dumbbell)',          primaryGroup: 'Back',       secondaryGroups: { Hamstrings: 0.5, Glutes: 0.5 } },
  { name: 'Seal Row - Dumbbell',                   primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Seated Cable Row (Home)',               primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Seated One Arm Cable Row',              primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'Seated Row (Cable)',                    primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Seated Row (Machine)',                  primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },
  { name: 'Seated Single Arm Low.Row',             primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5 } },
  { name: 'T Bar Row',                             primaryGroup: 'Back',       secondaryGroups: { Biceps: 0.5, Traps: 0.3 } },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────
  { name: 'Arnold Press (Dumbbell)',               primaryGroup: 'Shoulders',  secondaryGroups: { Triceps: 0.5 } },
  { name: 'Cable Crossbody Lateral Raise',         primaryGroup: 'Shoulders',  secondaryGroups: {} },
  { name: 'Clean (Barbell)',                        primaryGroup: 'Traps',      secondaryGroups: { Quads: 0.5, Glutes: 0.5, Hamstrings: 0.5, Shoulders: 0.5 } },
  { name: 'Face Pull (Cable)',                      primaryGroup: 'Shoulders',  secondaryGroups: { Back: 0.3 } },
  { name: 'Freemotion Cable Lateral Raises',       primaryGroup: 'Shoulders',  secondaryGroups: {} },
  { name: 'Full ROM Lateral Raises',               primaryGroup: 'Shoulders',  secondaryGroups: {} },
  { name: 'Hang Clean (Barbell)',                  primaryGroup: 'Traps',      secondaryGroups: { Quads: 0.5, Glutes: 0.5, Hamstrings: 0.5, Shoulders: 0.5 } },
  { name: 'Hang Power Clean',                      primaryGroup: 'Traps',      secondaryGroups: { Quads: 0.5, Glutes: 0.5, Hamstrings: 0.5, Shoulders: 0.5 } },
  { name: 'Lateral Raise (Cable)',                 primaryGroup: 'Shoulders',  secondaryGroups: {} },
  { name: 'Lateral Raise (Dumbbell)',              primaryGroup: 'Shoulders',  secondaryGroups: {} },
  { name: 'Overhead Press (Barbell)',              primaryGroup: 'Shoulders',  secondaryGroups: { Triceps: 0.5, Traps: 0.3 } },
  { name: 'Overhead Press (Dumbbell)',             primaryGroup: 'Shoulders',  secondaryGroups: { Triceps: 0.5 } },
  { name: 'Power Clean',                           primaryGroup: 'Traps',      secondaryGroups: { Quads: 0.5, Glutes: 0.5, Hamstrings: 0.5, Shoulders: 0.5 } },
  { name: 'Power Snatch (Barbell)',                primaryGroup: 'Traps',      secondaryGroups: { Quads: 0.5, Glutes: 0.5, Hamstrings: 0.5, Shoulders: 0.5 } },
  { name: 'Seated Dumbbell Lateral Raise',         primaryGroup: 'Shoulders',  secondaryGroups: {} },
  { name: 'Seated Dumbbell Shrugs',               primaryGroup: 'Shoulders',  secondaryGroups: { Traps: 0.5 } },
  { name: 'Seated Overhead Press Machine',         primaryGroup: 'Shoulders',  secondaryGroups: { Triceps: 0.5 } },
  { name: 'Shoulder Press (Machine)',              primaryGroup: 'Shoulders',  secondaryGroups: { Triceps: 0.5 } },
  { name: 'Shoulder Wall Stands',                  primaryGroup: 'Shoulders',  secondaryGroups: { Core: 0.3 } },
  { name: 'Strict Lateral Raise',                  primaryGroup: 'Shoulders',  secondaryGroups: {} },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────
  { name: 'Skullcrusher (Barbell)',                primaryGroup: 'Triceps',    secondaryGroups: {} },
  { name: 'Skullcrusher (Dumbbell)',               primaryGroup: 'Triceps',    secondaryGroups: {} },
  { name: 'Tricep Extension - Crossboy',           primaryGroup: 'Triceps',    secondaryGroups: {} },
  { name: 'Tricep Extension Standard',             primaryGroup: 'Triceps',    secondaryGroups: {} },
  { name: 'Tricep Extension Standing',             primaryGroup: 'Triceps',    secondaryGroups: {} },
  { name: 'Tricep Pushdowns - Banded',             primaryGroup: 'Triceps',    secondaryGroups: {} },
  { name: 'Tricep pushdowns - Rope',               primaryGroup: 'Triceps',    secondaryGroups: {} },
  { name: 'Triceps Extension (Cable)',             primaryGroup: 'Triceps',    secondaryGroups: {} },
  { name: 'Triceps Pushdown (Cable - Straight Bar)', primaryGroup: 'Triceps',  secondaryGroups: {} },

  // ─── BICEPS ───────────────────────────────────────────────────────────────
  { name: 'Bicep Curl (Barbell)',                  primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Bicep Curl (Cable)',                    primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Bicep Curl (Dumbbell)',                 primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Bicep Curl (Machine)',                  primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Concentration Curl (Dumbbell)',         primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'EZ Bar Curls',                          primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Forearm - Hammer',                      primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Forearm DB Curl',                       primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Freemotion Cable Curls',                primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Hammer Curl (Dumbbell)',                primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Incline Curl (Dumbbell)',               primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Preacher Curl (Barbell)',               primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Preacher Curl (Dumbbell)',              primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Preacher Curl Cable',                   primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Pronated Forearm Curls',                primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Seated Hammer Curls',                   primaryGroup: 'Biceps',     secondaryGroups: {} },
  { name: 'Standing Forearm Barbell Curls',        primaryGroup: 'Biceps',     secondaryGroups: {} },

  // ─── TRAPS ────────────────────────────────────────────────────────────────
  { name: 'Barbell Shrugs Wide Grip',              primaryGroup: 'Traps',      secondaryGroups: {} },
  { name: 'Shrug (Barbell)',                        primaryGroup: 'Traps',      secondaryGroups: {} },
  { name: 'Shrug (Dumbbell)',                       primaryGroup: 'Traps',      secondaryGroups: {} },
  { name: 'Shrug (Machine)',                        primaryGroup: 'Traps',      secondaryGroups: {} },
  { name: 'Smith Machine Shrugs',                  primaryGroup: 'Traps',      secondaryGroups: {} },
  { name: 'Snatch Grip Barbell Shrugs',            primaryGroup: 'Traps',      secondaryGroups: {} },

  // ─── CORE ─────────────────────────────────────────────────────────────────
  { name: 'Cable Chop (Upper)',                    primaryGroup: 'Core',       secondaryGroups: { Shoulders: 0.3 } },
  { name: 'Cable Crunch',                          primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Crunch (Machine)',                      primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Decline Crunch',                        primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Decline Situp',                         primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Dumbbell Front Rack Marches',           primaryGroup: 'Core',       secondaryGroups: { Quads: 0.3 } },
  { name: 'Dumbbell Overhead Marches',             primaryGroup: 'Core',       secondaryGroups: { Shoulders: 0.3 } },
  { name: 'Farmer Carry',                          primaryGroup: 'Core',       secondaryGroups: { Traps: 0.3 } },
  { name: 'Hanging Knee Raise',                    primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Hanging Leg Raise',                     primaryGroup: 'Core',       secondaryGroups: {} },
  { name: "Knee Raise (Captain's Chair)",          primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Kneeling Plate Rotation',               primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Lying Leg Crunches',                    primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Medball Core Rolls',                    primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Palloff Press',                         primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Side Plank',                            primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Single Leg Extension (Home)',           primaryGroup: 'Core',       secondaryGroups: { Quads: 0.3 } },
  { name: 'Sit Up',                                primaryGroup: 'Core',       secondaryGroups: {} },
  { name: 'Suitcase Carry',                        primaryGroup: 'Core',       secondaryGroups: { Traps: 0.3 } },
  { name: 'Suitcase Marches',                      primaryGroup: 'Core',       secondaryGroups: { Traps: 0.3 } },
  { name: 'Toes To Bar',                           primaryGroup: 'Core',       secondaryGroups: {} },

  // ─── QUADS ────────────────────────────────────────────────────────────────
  { name: 'Barbell split squat',                   primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Belt Cable Sissy Squat (Home)',         primaryGroup: 'Quads',      secondaryGroups: {} },
  { name: 'Belt Landmine Squat',                   primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Box Squat (Barbell)',                   primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Box Step Up',                           primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5 } },
  { name: 'Bulgarian Split Squat',                 primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Cossack Squat',                         primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3, Adductors: 0.3 } },
  { name: 'Freemotion - Narrow Stance Squats',     primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Freemotion Lunge',                      primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5 } },
  { name: 'Freemotion Squat Machine',              primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Freemotion Squat Partial Reps',         primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Goblet Squat (Kettlebell)',             primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3, Core: 0.3 } },
  { name: 'Hack Squat',                            primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Hack Squat (Barbell)',                  primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3, Hamstrings: 0.3 } },
  { name: 'Landmine Front Squat',                  primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3, Core: 0.3 } },
  { name: 'Leg Extension (Machine)',               primaryGroup: 'Quads',      secondaryGroups: {} },
  { name: 'Leg Extension Partials',                primaryGroup: 'Quads',      secondaryGroups: {} },
  { name: 'Leg Extensions (Home)',                 primaryGroup: 'Quads',      secondaryGroups: {} },
  { name: 'Leg Press',                             primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Leg Press - Single Leg',               primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Leg Press Partials',                    primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Lunge (Barbell)',                       primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Lunge (Bodyweight)',                    primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5 } },
  { name: 'Lunge (Dumbbell)',                      primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Pendulum Squat (Home)',                 primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Reverse Nordic Curl',                   primaryGroup: 'Quads',      secondaryGroups: {} },
  { name: 'Safety Squats',                         primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Sissy Squat',                           primaryGroup: 'Quads',      secondaryGroups: {} },
  { name: 'Smith Machine Hack Squat',              primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Split Squat - Dumbbell',               primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Squat (Barbell)',                       primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3, Core: 0.3 } },
  { name: 'Squat (Bodyweight)',                    primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3 } },
  { name: 'Squat (Smith Machine)',                 primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.5, Hamstrings: 0.3 } },
  { name: 'Suitcase Deadlift',                     primaryGroup: 'Quads',      secondaryGroups: { Glutes: 0.3, Core: 0.3 } },

  // ─── HAMSTRINGS ───────────────────────────────────────────────────────────
  { name: 'DB Sumo Deadlift',                      primaryGroup: 'Hamstrings', secondaryGroups: { Glutes: 0.5, Adductors: 0.3 } },
  { name: 'Dumbbell RDL',                          primaryGroup: 'Hamstrings', secondaryGroups: { Glutes: 0.5, Back: 0.3 } },
  { name: 'Kickstand RDL',                         primaryGroup: 'Hamstrings', secondaryGroups: { Glutes: 0.5 } },
  { name: 'Lying Leg Curl (Machine)',              primaryGroup: 'Hamstrings', secondaryGroups: {} },
  { name: 'Nordic Hamstring Curl',                 primaryGroup: 'Hamstrings', secondaryGroups: { Glutes: 0.3 } },
  { name: 'Rotational Kickstand Deadlift',         primaryGroup: 'Hamstrings', secondaryGroups: { Glutes: 0.5 } },
  { name: 'Seated Leg Curl (Machine)',             primaryGroup: 'Hamstrings', secondaryGroups: {} },
  { name: 'Seated Leg Press (Machine)',            primaryGroup: 'Hamstrings', secondaryGroups: { Glutes: 0.5, Quads: 0.3 } },
  { name: 'Single Leg RDL',                        primaryGroup: 'Hamstrings', secondaryGroups: { Glutes: 0.5 } },
  { name: 'Single kettlebell deadlift',            primaryGroup: 'Hamstrings', secondaryGroups: { Glutes: 0.5 } },
  { name: 'Standing Single Leg Curl',              primaryGroup: 'Hamstrings', secondaryGroups: {} },

  // ─── GLUTES ───────────────────────────────────────────────────────────────
  { name: 'Cable Adductor',                        primaryGroup: 'Glutes',     secondaryGroups: { Adductors: 0.5 } },
  { name: 'Cable Hip Thrusts (Home)',              primaryGroup: 'Glutes',     secondaryGroups: { Hamstrings: 0.3 } },
  { name: 'Clamshell oblique raises',              primaryGroup: 'Glutes',     secondaryGroups: { Abductors: 0.5 } },
  { name: 'Deadlift (Barbell)',                    primaryGroup: 'Glutes',     secondaryGroups: { Hamstrings: 0.5, Back: 0.5, Traps: 0.3 } },
  { name: 'Deadlift (Dumbbell)',                   primaryGroup: 'Glutes',     secondaryGroups: { Hamstrings: 0.5, Back: 0.3 } },
  { name: 'Glute Bridge',                          primaryGroup: 'Glutes',     secondaryGroups: { Hamstrings: 0.3 } },
  { name: 'Glute Kickback (Machine)',              primaryGroup: 'Glutes',     secondaryGroups: {} },
  { name: 'Hip Thrust (Barbell)',                  primaryGroup: 'Glutes',     secondaryGroups: { Hamstrings: 0.3 } },
  { name: 'Single Leg Bridge',                     primaryGroup: 'Glutes',     secondaryGroups: { Hamstrings: 0.3 } },
  { name: 'Single Leg Cable Kickback (Home)',      primaryGroup: 'Glutes',     secondaryGroups: {} },
  { name: 'Single Leg Glute Bridge',               primaryGroup: 'Glutes',     secondaryGroups: { Hamstrings: 0.3 } },
  { name: 'Single Leg Medial Glute Lateral Raise', primaryGroup: 'Glutes',     secondaryGroups: { Abductors: 0.5 } },
  { name: 'Trap Bar Deadlift',                     primaryGroup: 'Glutes',     secondaryGroups: { Hamstrings: 0.5, Quads: 0.3, Back: 0.3 } },

  // ─── CALVES ───────────────────────────────────────────────────────────────
  { name: 'Calf Press on Leg Press',               primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Calf Press on Seated Leg Press',        primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Seated Calf Press (Home)',              primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Seated Calf Raise (Machine)',           primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Seated Calf Raise (Plate Loaded)',      primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Smith Machine Standing Calf Raises',    primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Standing Calf Press - Single Leg',      primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Standing Calf Press Freemotion',        primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Standing Calf Raise (Barbell)',         primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Standing Calf Raise (Bodyweight)',      primaryGroup: 'Calves',     secondaryGroups: {} },
  { name: 'Standing Calf Raise (Dumbbell)',        primaryGroup: 'Calves',     secondaryGroups: {} },

  // ─── ABDUCTORS ────────────────────────────────────────────────────────────
  { name: 'Hip Abductor (Machine)',                primaryGroup: 'Abductors',  secondaryGroups: { Glutes: 0.3 } },

  // ─── ADDUCTORS ────────────────────────────────────────────────────────────
  { name: 'Hip Adductor (Machine)',                primaryGroup: 'Adductors',  secondaryGroups: {} },

  // ─── CARDIO ───────────────────────────────────────────────────────────────
  // Kept in library for logging; excluded from volume tracking and suggestion engine
  { name: 'Backwards Walking',                     primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Balance - Clock Touches',               primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Banded Jumps',                          primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Barbell Overhead Marches',              primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Box Jump',                              primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Burpee',                                primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Cycling (Indoor)',                      primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Drop Steps (Plyos)',                    primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Kettlebell Swing',                      primaryGroup: 'Cardio',     secondaryGroups: { Glutes: 0.3, Hamstrings: 0.3 } },
  { name: 'Lateral Side Jumps',                    primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Lateral Single Leg Pogo Hops',          primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Long Jump',                             primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Box Jump Height',               primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Box Push Off',                  primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Depth Jumps',                   primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Four Square Hops',              primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Kneeling Wall Slams',           primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Landmine Presses',              primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Pogo Hops',                     primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Rotational Wall Slams',         primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Single Leg Drop',               primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Single Leg Jump To Height',     primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo - Single Leg Line Hop',           primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyo Box Jump To Step Off',            primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Plyos - Lateral Jumps',               primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Pogo hops',                            primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Rowing (Machine)',                      primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Running',                               primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Running (Treadmill)',                   primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Sled Push',                             primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Snap Drop to Box Jump',                primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Stairmaster',                           primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Standing Jumps (Plyos)',               primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Walking',                               primaryGroup: 'Cardio',     secondaryGroups: {} },
  { name: 'Weighted Jumps',                        primaryGroup: 'Cardio',     secondaryGroups: {} },
];

// Quick lookup map: exercise name → library entry
// Used by the suggestion engine and volume tracker
export const EXERCISE_MAP = Object.fromEntries(
  EXERCISE_LIBRARY.map(e => [e.name, e])
);
